Algoritmo "exe07"
//Faça o mesmo que antes, porém, ao invés de ler 10 números, o programa
//deverá ler e somar números até que o valor digitado seja zero ( 0 ).
Var
cont, soma:inteiro

Inicio
// entrada
cont <- 1
enquanto (cont<>0) faca
     escreval("Digite um número para a soma:")
     escreval("OBS: Se o número for igual a zero, a soma será finalizada.")
     leia(cont)
     soma<-soma+cont
     escreval("Valor da soma: ", soma)
fimenquanto


Fimalgoritmo